config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'peaks/index'
  get 'signup' => 'users#new'
  get    'login'    => 'sessions#new'
  delete 'logout'   => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :peaks
  resources :microposts,          only: [:create, :destroy]
  resources :sessions,            only: [:new, :create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  

end

app/models/peak.rb
class Peak < ActiveRecord::Base
end

app/controllers/peaks_controller.rb
class PeaksController < ApplicationController
  before_action :set_peak, only: [:show, :edit, :update, :destroy]

  # GET /peaks
  # GET /peaks.json
  def index
    @peaks = Peak.all
  end

  # GET /peaks/1
  # GET /peaks/1.json
  def show
  end

  # GET /peaks/new
  def new
    @peak = Peak.new
  end

  # GET /peaks/1/edit
  def edit
  end

  # POST /peaks
  # POST /peaks.json
  def create
    @peak = Peak.new(peak_params)

    respond_to do |format|
      if @peak.save
        format.html { redirect_to @peak, notice: 'Peak was successfully created.' }
        format.json { render :show, status: :created, location: @peak }
      else
        format.html { render :new }
        format.json { render json: @peak.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peaks/1
  # PATCH/PUT /peaks/1.json
  def update
    respond_to do |format|
      if @peak.update(peak_params)
        format.html { redirect_to @peak, notice: 'Peak was successfully updated.' }
        format.json { render :show, status: :ok, location: @peak }
      else
        format.html { render :edit }
        format.json { render json: @peak.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peaks/1
  # DELETE /peaks/1.json
  def destroy
    @peak.destroy
    respond_to do |format|
      format.html { redirect_to peaks_url, notice: 'Peak was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peak
      @peak = Peak.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peak_params
      params.require(:peak).permit(:name, :altitude, :park)
    end
end

app/helpers/peaks_helper.rb
module PeaksHelper
end

app/views/peaks/_form.html.erb
<%= form_for(@peak) do |f| %>
  <% if @peak.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peak.errors.count, "error") %> prohibited this peak from being saved:</h2>

      <ul>
      <% @peak.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :altitude %><br>
    <%= f.number_field :altitude %>
  </div>
  <div class="field">
    <%= f.label :park %><br>
    <%= f.text_field :park %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peaks/edit.html.erb
<h1>Editing peak</h1>

<%= render 'form' %>

<%= link_to 'Show', @peak %> |
<%= link_to 'Back', peaks_path %>

app/views/peaks/index.html.erb
<h1>Listing peaks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Altitude</th>
      <th>Park</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peaks.each do |peak| %>
      <tr>
        <td><%= peak.name %></td>
        <td><%= peak.altitude %></td>
        <td><%= peak.park %></td>
        <td><%= link_to 'Show', peak %></td>
        <td><%= link_to 'Edit', edit_peak_path(peak) %></td>
        <td><%= link_to 'Destroy', peak, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peak', new_peak_path %>

app/views/peaks/new.html.erb
<h1>New peak</h1>

<%= render 'form' %>

<%= link_to 'Back', peaks_path %>

app/views/peaks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @peak.name %>
</p>

<p>
  <strong>Altitude:</strong>
  <%= @peak.altitude %>
</p>

<p>
  <strong>Park:</strong>
  <%= @peak.park %>
</p>

<%= link_to 'Edit', edit_peak_path(@peak) %> |
<%= link_to 'Back', peaks_path %>